export enum ExpenseTag {
    GROCERIES = 'GROCERIES',
    UTILITIES = 'UTILITIES',
    ENTERTAINMENT = 'ENTERTAINMENT',
    TRANSPORTATION = 'TRANSPORTATION',
    HEALTHCARE = 'HEALTHCARE',
    EDUCATION = 'EDUCATION',
    DINING = 'DINING',
    TRAVEL = 'TRAVEL',
    PERSONAL_CARE = 'PERSONAL_CARE',
    MISCELLANEOUS = 'MISCELLANEOUS'
}