openapi: 3.0.0
info:
  title: API CRUD - Expenses & Health
  version: 1.0.2
  description: |
    API de gestion des transactions et événements de santé.
  contact:
    name: Mesrop AGHUMYAN
    email: contact@mesrop-aghumyan.fr

servers:
  - url: http://localhost:3000
    description: Serveur de développement local
  - url: https://api.production.com/v1
    description: Serveur de production

tags:
  - name: Expenses
    description: Gestion des transactions financières
  - name: Health Events
    description: Suivi des événements médicaux

paths:
  /expenses:
    get:
      summary: Récupérer la liste des dépenses (paginée)
      tags:
        - Expenses
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/LimitParam'
        - name: tag
          in: query
          description: Filtrer par catégorie
          schema:
            $ref: '#/components/schemas/ExpenseTag'
          required: false
      responses:
        '200':
          description: Liste des dépenses récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Expense'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

    post:
      summary: Créer une nouvelle dépense
      tags:
        - Expenses
      requestBody:
        description: Données de la dépense à créer
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpenseInput'
      responses:
        '201':
          description: Dépense créée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Expense'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  /expenses/{id}:
    parameters:
      - $ref: '#/components/parameters/IdParam'
    get:
      summary: Récupérer une dépense spécifique
      tags:
        - Expenses
      responses:
        '200':
          description: Dépense trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Expense'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

    put:
      summary: Mettre à jour une dépense
      tags:
        - Expenses
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpenseInput'
      responses:
        '200':
          description: Dépense mise à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Expense'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

    delete:
      summary: Supprimer une dépense
      tags:
        - Expenses
      responses:
        '204':
          description: Dépense supprimée (pas de contenu retourné)
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

  /health-events:
    get:
      summary: Récupérer tous les événements de santé (paginé)
      tags:
        - Health Events
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/LimitParam'
      responses:
        '200':
          description: Liste des événements récupérée
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HealthEvent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

    post:
      summary: Créer un événement de santé
      tags:
        - Health Events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthEventInput'
      responses:
        '201':
          description: Événement créé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthEvent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  /health-events/{id}:
    parameters:
      - $ref: '#/components/parameters/IdParam'
    get:
      summary: Récupérer un événement de santé spécifique
      tags:
        - Health Events
      responses:
        '200':
          description: Événement trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthEvent'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

    put:
      summary: Mettre à jour un événement de santé
      tags:
        - Health Events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthEventInput'
      responses:
        '200':
          description: Événement mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthEvent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

    delete:
      summary: Supprimer un événement de santé
      tags:
        - Health Events
      responses:
        '204':
          description: Événement supprimé
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  parameters:
    PageParam:
      name: page
      in: query
      description: Numéro de la page (pagination)
      required: false
      schema:
        type: integer
        default: 1
        minimum: 1
    LimitParam:
      name: limit
      in: query
      description: Nombre d'éléments par page
      required: false
      schema:
        type: integer
        default: 20
        minimum: 1
        maximum: 100
    IdParam:
      name: id
      in: path
      required: true
      description: Identifiant unique de la ressource
      schema:
        type: string

  responses:
    BadRequest:
      description: Requête invalide (problème de validation)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Ressource non trouvée
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: Erreur interne du serveur
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    # --- Schéma d'erreur Standard ---
    Error:
      type: object
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: "La date de fin ne peut pas être avant la date de début."
        details:
          type: array
          items:
            type: string
          example: ["Champ 'amount' requis"]

    # --- Schemas Expense ---
    Expense:
      type: object
      required:
        - id
        - tag
        - isCredit
        - date
        - amount
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        tag:
          $ref: '#/components/schemas/ExpenseTag'
        isCredit:
          type: boolean
          example: true
          description: Vrai si c'est une entrée d'argent, Faux si dépense
        date:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
        amount:
          type: number
          format: double
          minimum: 0
          example: 125.50

    ExpenseInput:
      type: object
      required:
        - tag
        - isCredit
        - date
        - amount
      properties:
        tag:
          $ref: '#/components/schemas/ExpenseTag'
        isCredit:
          type: boolean
          description: "Définit si c'est un revenu ou une dépense"
          example: false
        date:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
        amount:
          type: number
          format: double
          minimum: 0.01
          example: 125.50

    ExpenseTag:
      type: string
      enum:
        - Loisir
        - Alimentaire
        - Loyer
        - Salaire
        - Investissement
        - Santé
        - Transport
      example: Loisir

    # --- Schemas Health ---
    HealthEvent:
      type: object
      required:
        - id
        - startDate
        - severity
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        startDate:
          type: string
          format: date-time
          example: "2024-01-15T08:00:00Z"
        endDate:
          type: string
          format: date-time
          nullable: true
          example: "2024-01-20T18:00:00Z"
        severity:
          $ref: '#/components/schemas/HealthEventSeverity'

    HealthEventInput:
      type: object
      required:
        - startDate
        - severity
      properties:
        startDate:
          type: string
          format: date-time
          example: "2024-01-15T08:00:00Z"
        endDate:
          type: string
          format: date-time
          nullable: true
          example: "2024-01-20T18:00:00Z"
        severity:
          $ref: '#/components/schemas/HealthEventSeverity'

    HealthEventSeverity:
      type: string
      enum:
        - Low
        - Medium
        - High
        - Critical
      example: Medium